jdbc-driver=com.mysql.cj.jdbc.Driver
#jdbc-url=jdbc:mysql://54.180.132.129:80/healthajo?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useUnicode=true&rewriteBatchedStatements=true&cachePrepStmts=true&prepStmtCacheSize=250&prepStmtCacheSqlLimit=2048&useServerPrepStmts=true
jdbc-url=jdbc:mysql://localhost:3306/healthajo?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useUnicode=true&allowMultiQueries=true&rewriteBatchedStatements=true&cachePrepStmts=true&prepStmtCacheSize=250&prepStmtCacheSqlLimit=2048&useServerPrepStmts=true
user=healthajo
password=healthajo12!@
pool-size=10
connection-timeout=30